[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[build]
rustflags = ["-C", "link-arg=-nostartfiles"]
target    = "xtensa-esp32s3-none-elf"

[env]
ESP_LOG = "info"

[unstable]
build-std = ["alloc", "core"]
