name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  ACT:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: esp-rs/xtensa-toolchain@v1.7.0
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: false

      - uses: Swatinem/rust-cache@v2
        if: ${{ !env.ACT }}

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --release --workspace --examples -- -D warnings

      - name: Build examples
        run: cargo build --release --workspace --examples

      - name: Docs
        run: cargo doc --no-deps --workspace
        env:
          RUSTDOCFLAGS: -D warnings

      - name: Package
        run: cargo package --workspace
